swagger: '2.0'
info:
  title: QbVIP backend
  description: QbVIP backend
  version: 1.0.0
paths:

  # 用户部分 start
  /v1/users:
    get:
      tags:
        - user
      description: 获取所有用户
      parameters:
        - in: header
          name: token
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '200':
          description: ''
        '400':
          description: no enough input
  /v1/users/{id}:
    get:
      tags:
        - user
      parameters:
        - in: header
          name: token
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: id
          description: 用户ID
      description: 获取某用户的信息
      responses:
        '200':
          description: ''
        '400':
          description: no enough input
    delete:
      tags:
        - user
      parameters:
        - in: header
          name: token
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: id
          description: 用户ID
      description: 删除用户
      responses:
        '200':
          description: ''
        '400':
          description: no enough input
  /v1/users/login:
    post:
      tags:
        - user
      description: 登录系统
      parameters:
        - in: header
          name: token
          schema:
            type: string
            format: uuid
          required: true
        - in: body
          name: body
          description: 用户信息
          schema:
            $ref: '#/definitions/userLogin'   
      responses:
        '200':
          description: ''
        '400':
          description: no enough input
  /v1/users/loginname/{loginName}:
    get:
      tags:
        - user
      parameters:
        - in: header
          name: token
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: loginName
          description: 用户登录名
      description: 根据用户登录名获取用户信息
      responses:
        '200':
          description: ''
        '400':
          description: no enough input
  /v1/users/registry:
    post:
      tags:
        - user
      description: 用户注册
      parameters:
        - in: body
          name: body
          description: 用户信息
          schema:
            $ref: '#/definitions/userinfo'
      responses:
        '200':
          description: ''
        '400':
          description: no enough input
  # 用户部分 end  

  # 网页收藏夹 start
  /v1/favorites/folder:
    get:
      tags:
        - favorites
      description: 获取所有收藏夹
      parameters:
        - in: header
          name: token
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '200':
          description: ''
        '400':
          description: no enough input
    post:
      tags:
        - favorites
      description: 添加收藏夹
      parameters:
        - in: header
          name: token
          schema:
            type: string
            format: uuid
          required: true
        - in: body
          name: body
          description: 收藏夹信息
          schema:
            $ref: '#/definitions/favorites_folder'
      responses:
        '200':
          description: ''
        '400':
          description: no enough input
  /v1/favorites/folder/{folderID}:
    get:
      tags:
        - favorites
      description: 列出该收藏夹下的所有地址
      parameters:
        - in: header
          name: token
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: folderID
          description: 收藏夹ID        
      responses:
        '200':
          description: ''
        '400':
          description: no enough input
    put:
      tags:
        - favorites
      description: 添加收藏夹
      parameters:
        - in: header
          name: token
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: folderID
          description: 收藏夹ID
        - in: body
          name: body
          description: 收藏夹信息
          schema:
            $ref: '#/definitions/favorites_folder'
      responses:
        '200':
          description: ''
        '400':
          description: no enough input
    delete:
      tags:
        - favorites
      description: 删除收藏夹文件夹
      parameters:
        - in: header
          name: token
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: id
          description: 收藏夹目录ID
      responses:
        '200':
          description: ''
        '400':
          description: no enough input

  /v1/favorites/folder/{folderID}/website:
    post:
      tags:
        - favorites
      description: 添加收藏夹
      parameters:
        - in: header
          name: token
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: folderID
          description: 收藏夹目录ID
        - in: body
          name: body
          description: 收藏夹信息
          schema:
            $ref: '#/definitions/favorites'
      responses:
        '200':
          description: ''
        '400':
          description: no enough input  
                    
  /v1/favorites/folder/{folderID}/website/{wsID}:
    put:
      tags:
        - favorites
      description: 编辑收藏夹
      parameters:
        - in: header
          name: token
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: folderID
          description: 收藏夹目录ID
        - in: path
          name: wsID
          description: 站点ID
        - in: body
          name: body
          description: 站点内容
          schema:
            $ref: '#/definitions/favorites'
      responses:
        '200':
          description: ''
        '400':
          description: no enough input
    delete:
      tags:
        - favorites
      description: 删除收藏夹
      parameters:
        - in: header
          name: token
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: folderID
          description: 收藏夹目录ID
        - in: path
          name: wsID
          description: 站点ID     
      responses:
        '200':
          description: ''
        '400':
          description: no enough input
  # 网页收藏夹 end


definitions:
  userLogin:
    type: object
    properties:
      loginName:
        type: string 
      password:
        type: string
  userinfo:
    type: object
    properties:
      loginName:
        type: string
      nikeName:
        type: string
      email:
        type: string
      password:
        type: string  
  favorites:
    type: object
    properties:      
      name:
        type: string 
      desc:
        type: string 
      label:
        type: array
      iconURL:
        type: string
      url:
        type: string
  favorites_folder:
    type: object
    properties:      
      name:
        type: string
      desc:
        type: string
      order:
        type: number
tags:
  - name: user
    description: 用户相关API
  - name: favorites
    description: 收藏站点
